//details page
import { useState, useEffect } from 'react';
import axios from 'axios';
import Head from 'next/head';
// components
import Navbar from '@/components/nav/Navbar';
import Nav from '@/components/sessions/Nav';
import Toolbar from '@/components/sessions/Toolbar';
import Instructor from '@/components/sessions/Instructor';
import Avatar from '@/components/sessions/Avatar';
import Amenities from '@/components/sessions/Amenities';
import Maps from '@/components/maps/Maps';
import Footer from '@/components/misc/Footer';
// data
//import sessions from '@/data/sessions';

export default function Instructors({ params }) {
  //  const session = sessions.find((session) => session.id === params.id);

  const [instructor, setInstructor] = useState([]);

  useEffect(() => {
    // GET request to fetch instructor by id from server
    axios
      .get(`http://localhost:3001/instructors/${params.id}`)
      .then((response) => {
        // Update the state with the fetched instructors
        setInstructor(response.data);
      })
      .catch((error) => {
        console.error('Error fetching instructors:', error);
      });
  }, [params.id]);
  return (
    <>
      <Head>
        <title>session details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {/* page layout */}
      <div className="layout h-100">
        <div className="container my-5">
          <div className="container-fluid">
            <Nav />
          </div>
          <div className="mt-3">
            <div className="container">
              <h3>{instructor.title}</h3>
            </div>
            <Toolbar instructors={instructor} />
            <div className="row gx-2">
              <div className="col-md-8">
                <Instructor instructors={instructor} />
              </div>
              <div className="col-md-4">
                <div className="d-flex justify-content-end">
                  <p className="text-white lh-3 fs-5 m-1">
                    {instructor.description}
                  </p>
                </div>
              </div>
            </div>
            <div className="container mt-5 py-4 my-4">
              <hr className="hr w-25 mx-auto pt-5" />
              <div className="row">
                <div className="col-md-6">
                  <div className="container">
                    <h3 className="fw-bold me-5 text-center">Amenities</h3>
                  </div>
                  <div className=" ">
                    <Amenities instructors={instructor} />
                  </div>
                </div>
                <div className="col-md-6">
                  <h3 className="fw-bold text-center">Locations</h3>
                  <Maps />
                  <div className="container d-flex justify-content-end fs-6 m-4"></div>
                </div>
              </div>
            </div>
          </div>
          <div className="container">
            <div className="row py-4">
              <div className="col-md-6">
                <h4 className=" text-center fw-normal text-white">
                  Personal Trainer: {instructor.name}
                </h4>
                <Avatar intructors={instructor} />
              </div>
              <div className="col-md-6">
                <h2 className="text-center fw-bold">About</h2>
                <div className="d-flex justify-content-end">
                  <p className="text-white lh-2 fs-5 m-1">{instructor.bio}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}

export async function getStaticPaths() {
  const paths = sessions.map((session) => ({
    params: { id: session.id.toString() },
  }));

  return { paths, fallback: false };
}

export async function getStaticProps({ params }) {
  return { props: { params } };
}
