// guides details page
import Head from 'next/head';
import { useEffect, useState } from 'react';
import axios from 'axios';
import { useRouter } from 'next/router';
import Navbar from '@/components/nav/Navbar';
import Nav from '@/components/guides/Nav';
import Avatar from '@/components/guides/Avatar';
import Bookings from '@/components/guides/tours/Bookings';
import Toolbar from '@/components/guides/Toolbar';
import Maps from '@/components/maps/Maps';
import Footer from '@/components/misc/Footer';

export default function Details({}) {
  const [guide, setGuide] = useState([]);
  const router = useRouter();
  const { id } = router.query;
  const [appointment, setAppointment] = useState([]);
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  // Fetch auth token
  useEffect(() => {
    const authToken = localStorage.getItem('authToken');
    if (authToken) {
      setIsLoggedIn(true);
    } else {
      setIsLoggedIn(false);
    }

    // Fetch tour guide details
    axios
      .get(`https://prime-fitness.onrender.com/guides/${id}`)
      .then((response) => {
        setGuide(response.data);
      })
      .catch((error) => {
        console.error('Error fetching tour guide details:', error);
      });

    // Fetch appointment by ud
    axios
      .get(`https://prime-fitness.onrender.com/appointments/${id}`)
      .then((response) => {
        setAppointment(response.data);
      })
      .catch((error) => {
        console.error('Error fetching appointments:', error);
      });
  }, [id]);
  return (
    <>
      <Head>
        <title>Prime Fitness | guide details page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div className="layout h-100">
        <div className="container-fluid pt-5">
          <Nav />
        </div>
        <section className=" shadow-lg rounded-3">
          <div className="container-fluid py-5">
            <div className="row py-3">
              <div className="col-md-6">
                <Avatar guides={guide} />
                <Toolbar guides={guide} />
              </div>
              <div className="col-lg-6">
                <div className="container-fluid ">
                  <h4 className="text-center display-5 fs-sm fw-normal">
                    {guide.name}
                  </h4>
                  <p className=" par d-flex justify-content-end fs-4 lh-2 fw-normal m-2 my-4">
                    {guide.bio}
                  </p>
                  <div className="d-flex justify-content-end p-2 me-5">
                    {isLoggedIn ? (
                      <Bookings appointments={appointment} guides={guide} />
                    ) : (
                      <div className="alert alert-warning">
                        You must be logged in to book an appointment.
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <div className="container-fluid my-5 pt-5">
          <h4 className="text-center display-5 mt-2 fs-sm pt-3 fw-normal">
            Locations
            <Maps />
          </h4>
        </div>
        <Footer />
      </div>
    </>
  );
}
