// guides details page
import Head from 'next/head';
import { useEffect, useState } from 'react';
import axios from 'axios';
// component imports
import Navbar from '@/components/nav/Navbar';
import Hero from '@/components/guides/Hero';
import Iconbar from '@/components/misc/Iconbar';
import Guides from '@/components/guides/Guides';
import Footer from '@/components/misc/Footer';
//import Reviews from '@/components/misc/Reviews';
// data
//import guides from '@/data/guides';

export default function Guide() {
  const [guides, setGuides] = useState([]); // initialize state variable for tour guides

  useEffect(() => {
    // Make a GET request to fetch tour guide data from server
    axios
      .get('http://localhost:3001/guides')
      .then((response) => {
        // Update the state with the fetched tour guide data
        setGuides(response.data);
      })
      .catch((error) => {
        console.error('Error fetching tour guides', error);
      });
  }, []);
  return (
    <>
      <Head>
        <title>Prime Fitness | tour guide page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="layout">
        <Hero />
        <div className="container py-5 mt-5">
          <div className="container col-lg-10 ">
            <h1 className="text-center text-white mt-3 display-4 pt-3 ">
              Schedule a Tour
            </h1>
            <p className="text-white text-center lead">
              Here at prime we beleive in flexiablity for every one see below
              which membership fits your need. Sign up for one of our daily
              tours and see why we were voted the number one fitness club in the
              area.
            </p>
          </div>

          <div className="mt-5">
            <Iconbar />
          </div>
          <hr className="hr" />
          <h1 className="text-white text-center py-5 my-5">Tour Guides</h1>
          <div className="row row-cols-1 row-cols-1 row-cols-lg-3 row-cols-md-4 g-4 py-5">
            {guides.map((guides) => (
              <div key={guides.id} className="py-3 my-3">
                <Guides className="" guides={guides} />
              </div>
            ))}
          </div>
          {/*}
          <Reviews />
          */}
        </div>
        <Footer />
      </div>
    </>
  );
}

// Fetch data using server side using getServerSideProps
export async function getServerSideProps() {
  try {
    const response = await axios.get('http://localhost:3001/guides');
    const guides = response.data;

    return {
      props: {
        guides,
      },
    };
  } catch (error) {
    console.error('Error fetching memberships', error);
    return {
      props: {
        guides: [],
      },
    };
  }
}
