//trainer bio page

import { useState, useEffect } from 'react';
import axios from 'axios';
import { useRouter } from 'next/router'; // Correct import statement
// imports
import Head from 'next/head';
import Navbar from '@/components/nav/Navbar';
import Nav from '@/components/trainers/Nav';
import Toolbar from '@/components/trainers/Toolbar';
import Trainer from '@/components/trainers/Trainer';
import Avatar from '@/components/trainers/Avatar';
import Amenities from '@/components/trainers/Amenities';
import Maps from '@/components/maps/Maps';
import Iconbar from '@/components/trainers/Iconbar';
import Footer from '@/components/misc/Footer';
import trainers from '@/data/trainers';

//

const Details = ({}) => {
  //  const trainer = trainers.find((trainer) => trainer.id === params.id);

  const [trainer, setTrainer] = useState([]); // initialize state variable for trainers
  const router = useRouter(); // Use the useRouter hook to access route parameters
  const { id } = router.query; // Get the 'id' parameter from the route

  useEffect(() => {
    if (id) {
      // Ensure 'id' is defined before making the API request
      axios
        .get(`http://localhost:3001/trainers/${id}`)
        .then((response) => {
          setTrainer(response.data);
        })
        .catch((error) => {
          console.error('Error fetching session:', error);
        });
    }
  }, [id]);
  return (
    <>
      <Head>
        <title>trainer details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {/* page layout */}
      <div className="layout h-100">
        <div className="container my-5">
          <div className="container-fluid">
            <Nav />
          </div>
          <div className="mt-3">
            <div className="container">
              <h3>{trainer.title}</h3>
            </div>
            <Toolbar trainers={trainer} />
            <div className="row gx-2">
              <div className="col-md-8">
                <Trainer trainers={trainer} />
              </div>
              <div className="col-md-4">
                <div className="d-flex justify-content-end">
                  <p className="text-white lh-3 fs-5 m-1">
                    {trainer.description}
                  </p>
                </div>
              </div>
            </div>
            <div className="container mt-5 py-4 my-4">
              <hr className="hr w-25 mx-auto pt-5" />
              <div className="row">
                <div className="col-md-6">
                  <div className="container">
                    <h3 className="fw-bold me-5 text-center">Amenities</h3>
                  </div>
                  <div className=" ">
                    <Amenities trainers={trainer} />
                  </div>
                </div>
                <div className="col-md-6">
                  <h3 className="fw-bold text-center">Locations</h3>
                  <Maps />
                  <div className="container d-flex justify-content-end fs-6 m-4"></div>
                </div>
              </div>
            </div>
          </div>
          <div className="container">
            <div className="row py-4">
              <div className="col-md-6">
                <h4 className=" text-center fw-normal text-white">
                  Personal Trainer: {trainer.name}
                </h4>
                <Avatar trainers={trainer} />
              </div>
              <div className="col-md-6">
                <h2 className="text-center fw-bold">About</h2>
                <div className="d-flex justify-content-end">
                  <p className="text-white lh-2 fs-5 m-1">{trainer.bio}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Details;

// Fetch data using server side using getServerSideProps
export async function getServerSideProps({ params }) {
  try {
    const response = await axios.get(
      `http://localhost:3001/trainers/${params.id}`
    );
    const trainer = response.data;

    return {
      props: {
        trainer,
      },
    };
  } catch (error) {
    console.error('Error fetching trainer details', error);
    return {
      props: {
        trainer: {},
      },
    };
  }
}
