// login page
import Link from 'next/link';
import { useState } from 'react';
import axios from 'axios';
//component imports
import Image from 'next/image';
import Head from 'next/head';
import Navbar from '@/components/nav/Navbar';
import jumbotron2 from '@/public/images/jumbotron/jumbotron2.jpg';

export default function Login() {
  const [formData, setFormData] = useState({
    email: '',
    password: '',
  });

  const [error, setError] = useState(null);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const response = await axios.post(
        'http://localhost:3001/auth/login',
        formData
      );

      if (response.status === 200) {
        window.location.href = '/user';
      } else {
        const data = response.data;
        setError(data.message);
      }
    } catch (err) {
      console.error(err);
      setError('Internal server error');
    }
  };

  // Add Google login function
  const handleGoogleLogin = () => {
    window.location.href = 'http://localhost:3001/auth/google/login';
  };

  // Facebook registration function
  const handleFacebookLogin = () => {
    const facebookOAuthURL = 'http://localhost:3001/auth/facebook/login';

    window.open(
      facebookOAuthURL,
      'Facebook OAuth',
      'align-item-center',
      'width=300,height=300'
    );
  };
  return (
    <>
      <Head>
        <title>Prime Fitness | login page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="layout h-100">
        <div className="container py-5">
          <hr className="hr " />
          <div className="container col-xxl-8 px-4 py-5 ">
            <div className="row flex-lg-row-reverse align-items-center g-5">
              <div className="col-10 col-sm-8 col-lg-6 mb-5">
                <Image
                  src={jumbotron2}
                  className=" img-fluid image"
                  alt="img"
                  width={500}
                  height={335}
                  loading="lazy"
                />
              </div>

              <div className="col-lg-6 mb-5 ">
                <h4 className="text-dark text-center">Login to your Account</h4>

                <p className=" text-center">
                  {" Don't have an account?"}
                  <Link
                    className="btn btn-lg badge me-2"
                    href="/register/Register"
                  >
                    Register
                  </Link>
                </p>
                <form className="form text-center" onSubmit={handleSubmit}>
                  <input
                    className="form-control m-2 fw-bold"
                    type="email"
                    placeholder="email"
                    value={formData.email}
                    onChange={handleChange}
                  />
                  <input
                    className="form-control m-2 fw-bold"
                    type="password"
                    placeholder="Password"
                    value={formData.password}
                    onChange={handleChange}
                  />
                  <div className="container mt-3">
                    <button className="w-100 btn btn-md" type="submit">
                      Login
                    </button>
                  </div>
                  <h6 className="text-muted pt-3">or login with</h6>
                  <ul className="nav justify-content-center list-unstyled d-flex pt-2">
                    <li className="ms-3">
                      <button
                        className="text-muted bg-transparent border-0"
                        onClick={handleFacebookLogin}
                      >
                        <i className="social-icons fa-brands fa-facebook-f m-2"></i>
                      </button>
                    </li>
                    <li className="ms-3">
                      <button
                        className="text-muted bg-transparent border-0"
                        onClick={handleGoogleLogin}
                      >
                        <i className="social-icons fa-brands fa-google m-2"></i>
                      </button>
                    </li>
                  </ul>
                  <div className="container mt-3"></div>
                  <p className="par text-dark mt-5 mb-3">
                    &copy; Prime Fitness, 2025
                  </p>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
