// register page
import Link from 'next/link';
import { useState, useEffect } from 'react';
import axios from 'axios';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import Head from 'next/head';
//component imports
import Navbar from '@/components/nav/Navbar';
import jumbotron3 from '@/public/images/jumbotron/jumbotron3.jpg';

export default function Register() {
  const router = useRouter();
  const [formData, setFormData] = useState({
    fullName: '',
    email: '',
    password: '',
    confirmPassword: '',
  });

  const [errorMessage, setErrorMessage] = useState('');
  const [successMessage, setSuccessMessage] = useState('');

  // Handle form data change
  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const response = await axios.post(
        'https://fitness-server-c1a2fb04992c.herokuapp.com/auth/register',
        formData
      );

      if (response.status === 201) {
        const { token } = response.data;
        localStorage.setItem('token', token);

        if (response.data.redirectTo) {
          router.push(response.data.redirectTo);
        }

        setSuccessMessage('Registration successful!.');
      } else {
        setErrorMessage(response.data.message);
      }
    } catch (error) {
      console.error('Error during registration:', error);
      setErrorMessage('Internal server error');
    }
  };
  // Google registration function
  const handleGoogleRegister = () => {
    const googleOAuthURL =
      'https://fitness-server-c1a2fb04992c.herokuapp.com/googleAuth/google/register';

    window.open(
      googleOAuthURL,
      'Google OAuth',
      'align-item-center',
      'width=300,height=300'
    );
  };
  // facebook registration function

  const handleFacebookRegister = () => {
    const facebookOAuthURL =
      'https://fitness-server-c1a2fb04992c.herokuapp.com/auth/facebook/register';

    window.open(
      facebookOAuthURL,
      'Facebook OAuth',
      'align-item-center',
      'width=300,height=300'
    );
  };
  // end of oAuth registration function
  return (
    <>
      <Head>
        <title>Prime Fitness | register page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="container py-5">
        <hr className="hr " />
        <div className="container col-xxl-8 px-4 py-4 ">
          <div className="row flex-lg-row-reverse align-items-center g-5 ">
            <div className="col-10 col-sm-8 col-lg-6 ">
              <Image
                src={jumbotron3}
                className=" img-fluid image m-4"
                alt="img"
                width={500}
                height={335}
                loading="lazy"
              />
            </div>

            <div className="col-lg-6">
              <h2 className="fw-bold text-center">Create your Account</h2>

              <p className=" text-center text-white">
                Already have an account?{' '}
                <Link className="btn btn-lg badge" href="/login/Login">
                  Login.
                </Link>
              </p>

              <form className="form text-center" onSubmit={handleSubmit}>
                <input
                  className="form-control m-2 fw-bold"
                  required
                  type="text"
                  name="fullName"
                  value={formData.fullName}
                  onChange={handleChange}
                  placeholder="Enter Full Name"
                />
                <input
                  className="form-control m-2 fw-bold"
                  required
                  type="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  placeholder="Enter Email"
                />
                <input
                  className="form-control m-2 fw-bold"
                  required
                  type="password"
                  name="password"
                  value={formData.password}
                  onChange={handleChange}
                  placeholder="Enter Password"
                />
                <input
                  className="form-control m-2 fw-bold"
                  required
                  type="password"
                  name="confirmPassword"
                  value={formData.confirmPassword}
                  onChange={handleChange}
                  placeholder="Confirm Password"
                />

                <div className="container mt-3">
                  {errorMessage && (
                    <p className="text-danger">{errorMessage}</p>
                  )}
                  {successMessage && (
                    <p className="text-success">{successMessage}</p>
                  )}
                  <button className="w-100 btn btn-md" type="submit">
                    register
                  </button>
                </div>
                <div className="container mt-3">
                  <button
                    className="w-100 btn btn-md"
                    type="submit"
                    onClick={handleFacebookRegister}
                  >
                    <i className="fab fa-fw fa-facebook-f text-facebook me-2"></i>
                    Register with Facebook
                  </button>
                </div>
                <div className="container mt-3">
                  <button
                    className="w-100 btn btn-md"
                    type="submit"
                    onClick={handleGoogleRegister}
                  >
                    <i className="fab fa-fw fa-google text-google-icon me-2"></i>
                    Register with Google
                  </button>
                </div>

                <p className="mt-5 mb-3 text-white">
                  &copy; Prime Fitness, 2024
                </p>
              </form>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
