import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head';
import Navbar from '@/components/nav/Navbar';
import jumbotron3 from '@/public/images/jumbotron/jumbotron3.jpg';

export default function Register() {
  return (
    <>
      <Head>
        <title>Prime Fitness | register page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="position-relative h-100 pt-5 pb-4">
        <div className="container d-flex flex-wrap justify-content-center justify-content-xl-start h-100 pt-5">
          <div
            className="w-100 align-self-end pt-1 pt-md-4 pb-4"
            style={{ maxWidth: '526px' }}
          >
            <h1 className="text-center text-xl-start">Create Account</h1>
            <p className="text-center text-xl-start pb-3 mb-3 text-white">
              Already have an account?{' '}
              <Link className="btn btn-sm " href="/login/Login">
                Login.
              </Link>
            </p>
            <form className="needs-validation" novalidate>
              <div className="row ">
                <div className="col-sm-6">
                  <div className="position-relative mb-4">
                    <label for="name" className="form-label fs-base text-white">
                      First name
                    </label>
                    <input
                      type="text"
                      id="name"
                      className="form-control form-control-lg text-dark fs-6"
                      placeholder="first name"
                      required
                    />
                    <div className="invalid-feedback position-absolute start-0 top-100 text-white">
                      Last Name
                    </div>
                  </div>
                </div>
                <div className="col-sm-6">
                  <div className="position-relative mb-4">
                    <label for="name" className="form-label fs-base text-white">
                      Last name
                    </label>
                    <input
                      type="text"
                      id="name"
                      className="form-control form-control-lg fs-6"
                      placeholder="last name"
                      required
                    />
                    <div className="invalid-feedback position-absolute start-0 top-100">
                      Please enter your name!
                    </div>
                  </div>
                </div>
                <div className="col-sm-6">
                  <div className="position-relative mb-4">
                    <label
                      for="email"
                      className="form-label fs-base text-white"
                    >
                      Email
                    </label>
                    <input
                      type="email"
                      id="email"
                      className="form-control form-control-lg fs-6"
                      placeholder="email"
                      required
                    />
                    <div className="invalid-feedback position-absolute start-0 top-100">
                      <h6 className="text-white">
                        Please enter a valid email address!
                      </h6>
                    </div>
                  </div>
                </div>
                <div class="col-12 mb-4">
                  <label
                    for="password"
                    className="form-label fs-base text-white"
                  >
                    Password
                  </label>
                  <div className="password-toggle">
                    <input
                      type="password"
                      id="password"
                      className="form-control form-control-lg fs-6"
                      placeholder="Enter your password"
                      required
                    />
                    <label
                      className="password-toggle-btn"
                      aria-label="Show/hide password"
                    >
                      <input
                        className="password-toggle-check"
                        type="checkbox"
                      />
                      <span className="password-toggle-indicator"></span>
                    </label>
                    <div className="invalid-feedback position-absolute start-0 top-100">
                      Please enter a password!
                    </div>
                  </div>
                </div>
                <div className="col-12 mb-4">
                  <label
                    for="password-confirm"
                    className="form-label fs-base text-white"
                  >
                    Confirm password
                  </label>
                  <div className="password-toggle">
                    <input
                      type="password"
                      id="password-confirm"
                      className="form-control form-control-lg fs-6"
                      placeholder="Confirm your password"
                      required
                    />
                    <label
                      className="password-toggle-btn"
                      aria-label="Show/hide password"
                    >
                      <input
                        className="password-toggle-check"
                        type="checkbox"
                      />
                      <span className="password-toggle-indicator"></span>
                    </label>
                    <div className="invalid-feedback position-absolute start-0 top-100">
                      Please enter a password!
                    </div>
                  </div>
                </div>
              </div>
              <div className="mb-4">
                <div className="form-check">
                  <input
                    type="checkbox"
                    id="terms"
                    className="form-check-input"
                  />
                  <label
                    for="terms"
                    className="form-check-label fs-base text-white"
                  >
                    I agree to <Link href="#">Terms &amp; Conditions</Link>
                  </label>
                </div>
              </div>
              <Link href="/" type="submit" className="btn btn-lg w-100">
                Sign up
              </Link>
            </form>
            <hr className="my-4" />
            <h6 className="text-center mb-4">
              Or sign up with your social network
            </h6>
            <div className="row row-cols-1 row-cols-sm-2">
              <div className="col mb-3">
                <Link
                  href="/"
                  className="btn btn-icon btn-secondary btn-google btn-lg w-100"
                >
                  <i className="bx bxl-google fs-xl me-2"></i>
                  Google
                </Link>
              </div>
              <div className="col mb-3">
                <Link
                  href="/"
                  className="btn btn-icon btn-secondary btn-facebook btn-lg w-100"
                >
                  <i className="bx bxl-facebook fs-xl me-2"></i>
                  Facebook
                </Link>
              </div>
            </div>
          </div>
          <div className="w-100 align-self-end">
            <p className="nav text-white d-block fs-xs text-center text-xl-start pb-2 mb-0">
              &copy; 2023
              <Link
                className="nav-link d-inline-block p-0"
                href="/"
                target="_blank"
                rel="noopener"
              >
                Prime Fitness
              </Link>
            </p>
          </div>
        </div>
        <div className="register container position-absolute top-0 end-0 w-50 h-100 bg-position-center bg-repeat-0 bg-size-cover d-none d-xl-block">
          <div className=""></div>
        </div>
      </div>
    </>
  );
}
