export const CALENDAR_ADD_APPOINTMENT = 'CALENDAR_ADD_APPOINTMENT';
export const CALENDAR_CHANGE_TIME = 'CALENDAR_CHANGE_TIME';
export const CALENDAR_CANCEL_APPOINTMENT = 'CALENDAR_CANCEL_APPOINTMENT';
export const CALENDAR_CHANGE_APPOINTMENT = 'CALENDAR_CHANGE_APPOINTMENT';
export const CALENDAR_SAVE_APPOINTMENT = 'CALENDAR_SAVE_APPOINTMENT';
