// owner details page
import Head from 'next/head';
import { useEffect, useState } from 'react';
import axios from 'axios';
import { useRouter } from 'next/router';
import Navbar from '@/components/nav/Navbar';
import Nav from '@/components/owners/Nav';
import Bio from '@/components/owners/Bio';
import Toolbar from '@/components/owners/Toolbar';
import Maps from '@/components/maps/Maps';
import Footer from '@/components/misc/Footer';

export default function OwnerDetails({}) {
  const [owner, setOwner] = useState([]);
  const router = useRouter();
  const { id } = router.query;

  useEffect(() => {
    if (id) {
      axios
        .get(`https://prime-fitness.onrender.com/owners/${id}`)
        .then((response) => {
          setOwner(response.data);
        })
        .catch((error) => {
          console.error('Error fetching owner by id', error);
        });
    }
  }, [id]);
  return (
    <>
      <Head>
        <title>Prime Fitness | staff page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="layout py-2">
        <div className="container py-5">
          <Nav />
          <div className="row py-3">
            <div className="col-md-6">
              <h4 className="display-5 mt-2 fs-sm pt-3 fw-normal">
                {owner.title}
              </h4>
              <Bio owners={owner} />
              <Toolbar owners={owner} />
            </div>
            <div className="col-lg-6">
              <div className="container-fluid ">
                <h4 className="text-center display-5 mt-2 fs-sm pt-3 fw-normal">
                  {owner.name}
                </h4>
                <p className=" par d-flex justify-content-end fs-4 lh-2 fw-normal m-2  my-4">
                  {owner.bio}
                </p>
                <div className="d-flex justify-content-end p-2 me-5"></div>
              </div>
            </div>
          </div>
          <div className="container-fluid">
            <h4 className="text-center display-5 mt-2 fs-sm pt-3 fw-normal">
              Locations
              <Maps />
            </h4>
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
}

// getServerSideProps
export async function getServerSideProps({ params }) {
  try {
    const response = await axios.get(
      `https://prime-fitness.onrender.com/owners/${params.id}`
    );
    const owner = response.data;

    return {
      props: {
        owner,
      },
    };
  } catch (error) {
    console.error('Error fetching owner details', error);
    return {
      props: {
        owner: {},
      },
    };
  }
}
