// trainers page
import Head from 'next/head';
import Navbar from '@/components/nav/Navbar';
import Hero from '@/components/owners/Hero';
import Owners from '@/components/owners/Owners';
import Features from '@/components/misc/Features';
import Details from '@/components/misc/Details';
import Footer from '@/components/misc/Footer';

export default function Owner() {
  const [owners, setOwners] = useState([]);

  useEffect(() => {
    axios
      .get('https://prime-fitness.onrender.com/owners')
      .then((response) => {
        setOwners(response.data);
      })
      .catch((error) => {
        console.error('Error fetching owners:', error);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Prime Fitness | owners page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="layout">
        <Hero />
        <div className="container col-lg-10 m-auto my-5 py-5">
          <h1 className="text-center text-white mt-3 display-4">
            Meet the owners
          </h1>
          <p className="text-white text-center lead ">
            Here at prime we beleive in flexiablity for every one see below
            which membership fits your need. Sign up for one of our daily tours
            and see why we were voted the number one fitness club in the area.
          </p>
        </div>

        <div className="container m-auto my-5 py-5">
          <hr className="hr" />
          <h1 className="text-white text-center py-5 my-5">Owners</h1>
          <div className="row row-cols-sm-2 row-cols-1 gy-3 gx-4 mb-4 pb-md-2 my-5 h-32 py-3">
            {owners.map((owners) => (
              <div key={owners.id} className="py-3 my-3">
                <Owners className="" owners={owners} />
              </div>
            ))}
          </div>
        </div>
        <Features />
        <Details />
        <Footer />
      </div>
    </>
  );
}

// Fetch data using server side using getServerSideProps
export async function getServerSideProps() {
  try {
    const response = await axios.get(
      'https://prime-fitness.onrender.com/owners'
    );
    const owners = response.data;

    return {
      props: {
        owners,
      },
    };
  } catch (error) {
    console.error('Error fetching owners', error);
    return {
      props: {
        owners: [],
      },
    };
  }
}
