// team page
import Head from 'next/head';
import { useEffect, useState } from 'react';
import axios from 'axios';
// component imports
import Navbar from '@/components/nav/Navbar';
import Hero from '@/components/team/Hero';
import Profile from '@/components/trainers/Profile';
import Teams from '@/components/sessions/Teams';
import Guides from '@/components/team/Guides';
import Owners from '@/components/owners/Owners';
import Iconbar from '@/components/misc/Iconbar';
import Footer from '@/components/misc/Footer';

export default function Team() {
  const [owners, setOwners] = useState([]);
  const [guides, setGuides] = useState([]);
  const [sessions, setSessions] = useState([]);
  const [trainers, setTrainers] = useState([]);

  useEffect(() => {
    axios
      .get('http://localhost:3001/owners')
      .then((response) => {
        setOwners(response.data);
      })
      .catch((error) => {
        console.error('Error fetching owners:', error);
      });
  }, []);

  useEffect(() => {
    axios
      .get('http://localhost:3001/guides')
      .then((response) => {
        setGuides(response.data);
      })
      .catch((error) => {
        console.error('Error fetching tour guides', error);
      });
  }, []);

  useEffect(() => {
    axios
      .get('http://localhost:3001/sessions')
      .then((response) => {
        setSessions(response.data);
      })
      .catch((error) => {
        console.error('Error fetching instructors:', error);
      });
  }, []);

  useEffect(() => {
    axios
      .get('http://localhost:3001/trainers')
      .then((response) => {
        setTrainers(response.data);
      })
      .catch((error) => {
        console.error('Error fetching instructors:', error);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Prime Fitness | staff page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="layout">
        <Hero />
        <div className="container py-5 mt-5">
          <div className="container col-lg-10 ">
            <h1 className="text-center mt-3 display-4 pt-3 ">Meet our Staff</h1>
            <p className="par text-center lead">
              Here at prime we beleive in flexiablity for every one see below
              which membership fits your need. Sign up for one of our daily
              tours and see why we were voted the number one fitness club in the
              area.
            </p>
          </div>

          <div className="mt-5">
            <Iconbar />
          </div>

          <h1 className=" text-center py-5 my-5">Owners</h1>
          <div className="row row-cols-sm-2 row-cols-1 gy-3 gx-4 mb-4 pb-md-2 my-5 h-32 py-3 pt-3">
            {owners.map((owners) => (
              <div key={owners.id} className="py-3 my-5">
                <Owners className="" owners={owners} />
              </div>
            ))}
          </div>
          <hr className="hr" />
          <h1 className=" text-center py-3 my-3">Tour Guides</h1>
          <div className="row row-cols-1 row-cols-1 row-cols-lg-3 row-cols-md-4 g-4 py-5 pt-3">
            {guides.map((guides) => (
              <div key={guides.id} className="py-3 my-3">
                <Guides className="" guides={guides} />
              </div>
            ))}
          </div>
          <hr className="hr" />
          <h1 className=" py-3 my-3">Class Instructors</h1>
          <div className="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 py-5 pt-3">
            {sessions.map((sessions) => (
              <div key={sessions.id} className="py-3 my-5">
                <Teams className="" sessions={sessions} />
              </div>
            ))}
          </div>
          <hr className="hr" />
          <h1 className=" text-center py-3 my-3">Personal Trainers</h1>
          <div className="row row-cols-1 row-cols-1 row-cols-lg-3 row-cols-lg-4 g-4 py-5 ">
            {trainers.map((trainers) => (
              <div key={trainers.id} className="py-3 my-5">
                <Profile className="" trainers={trainers} />
              </div>
            ))}
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
}
