import Head from 'next/head';

import products from '@/data/products';
import FeaturedProducts from '@/components/products/FeaturedProducts';

export default function Products() {
  return (
    <>
      <Head>
        <title>Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Test</h1>
        <div className="row row-cols-1 row-cols-1 row-cols-lg-3 row-cols-lg-4 g-4 py-4">
          {products.map((products) => (
            <div key={products.id} className="pt-4 ">
              <FeaturedProducts products={products} />
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
