// profile page
import Head from 'next/head';
import { useEffect, useState } from 'react';
import axios from 'axios';
import Link from 'next/link';
import Navbar from '@/components/nav/Navbar';
import Footer from '@/components/misc/Footer';

export default function Users({}) {
  const [users, setUsers] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    axios
      .get(`https://fitness-server-c1a2fb04992c.herokuapp.com/auth/`)
      .then((response) => {
        setUsers(response.data);
      })
      .catch((error) => {
        console.error('Error fetching users:', error);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Prime Fitness | success</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="container py-5">
        <hr className="hr " />

        <div className="layout">
          <div className="container-fluid pt-5">
            <div className="container-fluid pt-5">
              {/* sidebar */}
              <div className="row">
                <aside className="col-lg-3 col-md-4 border-end pb-5 mt-n5">
                  <div className="position-sticky top-0">
                    <div className="text-center pt-5">
                      <div className="d-table position-relative mx-auto mt-2 mt-lg-4 pt-5 mb-3">
                        {/* test image */}
                        <button className="btn btn-md btn-accent d-block w-75 m-auto mt-3">
                          Refresh
                        </button>
                      </div>
                      <h2 className="fw-bold">{users?.fullName}</h2>
                      {users && <p className="fw-normal">{users.fullName}</p>}
                      {/* Display other user information */}
                    </div>
                  </div>
                </aside>
              </div>
              {/* main content */}
              <div className="col-lg-9 col-md-8">
                <div>
                  {error && <p>Error: {error}</p>}
                  {users && (
                    <>
                      <h2>{users.fullName}&apos;s Profile</h2>
                    </>
                  )}
                </div>
              </div>
            </div>
          </div>
          <Footer />
        </div>
      </div>
    </>
  );
}
