export const GUIDE_LIST_REQUEST = ' GUIDE_LIST_REQUEST';
export const GUIDE_LIST_SUCCESS = ' GUIDE_LIST_SUCCESS';
export const GUIDE_LIST_FAIL = ' GUIDE_LIST_FAIL';

export const GUIDE_DETAILS_REQUEST = ' GUIDE_DETAILS_REQUEST';
export const GUIDE_DETAILS_SUCCESS = ' GUIDE_DETAILS_SUCCESS';
export const GUIDE_DETAILS_FAIL = ' GUIDE_DETAILS_FAIL';

export const GUIDE_DELETE_REQUEST = ' GUIDE_DELETE_REQUEST';
export const GUIDE_DELETE_SUCCESS = ' GUIDE_DELETE_SUCCESS';
export const GUIDE_DELETE_FAIL = ' GUIDE_DELETE_FAIL';

export const GUIDE_CREATE_REQUEST = ' GUIDE_CREATE_REQUEST';
export const GUIDE_CREATE_SUCCESS = ' GUIDE_CREATE_SUCCESS';
export const GUIDE_CREATE_FAIL = ' GUIDE_CREATE_FAIL';
export const GUIDE_CREATE_RESET = ' GUIDE_CREATE_RESET';

export const GUIDE_UPDATE_REQUEST = ' GUIDE_UPDATE_REQUEST';
export const GUIDE_UPDATE_SUCCESS = ' GUIDE_UPDATE_SUCCESS';
export const GUIDE_UPDATE_FAIL = ' GUIDE_UPDATE_FAIL';
export const GUIDE_UPDATE_RESET = ' GUIDE_UPDATE_RESET';

export const GUIDE_CREATE_REVIEW_REQUEST = ' GUIDE_CREATE_REVIEW_REQUEST';
export const GUIDE_CREATE_REVIEW_SUCCESS = ' GUIDE_CREATE_REVIEW_SUCCESS';
export const GUIDE_CREATE_REVIEW_FAIL = ' GUIDE_CREATE_REVIEW_FAIL';
export const GUIDE_CREATE_REVIEW_RESET = ' GUIDE_CREATE_REVIEW_RESET';

export const GUIDE_TOP_REQUEST = ' GUIDE_TOP_REQUEST';
export const GUIDE_TOP_SUCCESS = ' GUIDE_TOP_SUCCESS';
export const GUIDE_TOP_FAIL = ' GUIDE_TOP_FAIL';
