export const MEMBER_LIST_REQUEST = 'MEMBER_LIST_REQUEST';
export const MEMBER_LIST_SUCCESS = 'MEMBER_LIST_SUCCESS';
export const MEMBER_LIST_FAIL = 'MEMBER_LIST_FAIL';

export const MEMBER_DETAILS_REQUEST = 'MEMBER_DETAILS_REQUEST';
export const MEMBER_DETAILS_SUCCESS = 'MEMBER_DETAILS_SUCCESS';
export const MEMBER_DETAILS_FAIL = 'MEMBER_DETAILS_FAIL';

export const MEMBER_DELETE_REQUEST = 'MEMBER_DELETE_REQUEST';
export const MEMBER_DELETE_SUCCESS = 'MEMBER_DELETE_SUCCESS';
export const MEMBER_DELETE_FAIL = 'MEMBER_DELETE_FAIL';

export const MEMBER_CREATE_REQUEST = 'MEMBER_CREATE_REQUEST';
export const MEMBER_CREATE_SUCCESS = 'MEMBER_CREATE_SUCCESS';
export const MEMBER_CREATE_FAIL = 'MEMBER_CREATE_FAIL';
export const MEMBER_CREATE_RESET = 'MEMBER_CREATE_RESET';

export const MEMBER_UPDATE_REQUEST = 'MEMBER_UPDATE_REQUEST';
export const MEMBER_UPDATE_SUCCESS = 'MEMBER_UPDATE_SUCCESS';
export const MEMBER_UPDATE_FAIL = 'MEMBER_UPDATE_FAIL';
export const MEMBER_UPDATE_RESET = 'MEMBER_UPDATE_RESET';

export const MEMBER_CREATE_REVIEW_REQUEST = 'MEMBER_CREATE_REVIEW_REQUEST';
export const MEMBER_CREATE_REVIEW_SUCCESS = 'MEMBER_CREATE_REVIEW_SUCCESS';
export const MEMBER_CREATE_REVIEW_FAIL = 'MEMBER_CREATE_REVIEW_FAIL';
export const MEMBER_CREATE_REVIEW_RESET = 'MEMBER_CREATE_REVIEW_RESET';

export const MEMBER_TOP_REQUEST = 'MEMBER_TOP_REQUEST';
export const MEMBER_TOP_SUCCESS = 'MEMBER_TOP_SUCCESS';
export const MEMBER_TOP_FAIL = 'MEMBER_TOP_FAIL';
