export const OWNER_LIST_REQUEST = 'OWNER__LIST_REQUEST';
export const OWNER__LIST_SUCCESS = 'OWNER__LIST_SUCCESS';
export const OWNER__LIST_FAIL = 'OWNER__LIST_FAIL';

export const OWNER__DETAILS_REQUEST = 'OWNER__DETAILS_REQUEST';
export const OWNER__DETAILS_SUCCESS = 'OWNER__DETAILS_SUCCESS';
export const OWNER__DETAILS_FAIL = 'OWNER__DETAILS_FAIL';

export const OWNER__DELETE_REQUEST = 'OWNER__DELETE_REQUEST';
export const OWNER__DELETE_SUCCESS = 'OWNER__DELETE_SUCCESS';
export const OWNER__DELETE_FAIL = 'OWNER__DELETE_FAIL';

export const OWNER__CREATE_REQUEST = 'OWNER__CREATE_REQUEST';
export const OWNER__CREATE_SUCCESS = 'OWNER__CREATE_SUCCESS';
export const OWNER__CREATE_FAIL = 'OWNER__CREATE_FAIL';
export const OWNER__CREATE_RESET = 'OWNER__CREATE_RESET';

export const OWNER__UPDATE_REQUEST = 'OWNER__UPDATE_REQUEST';
export const OWNER__UPDATE_SUCCESS = 'OWNER__UPDATE_SUCCESS';
export const OWNER__UPDATE_FAIL = 'OWNER__UPDATE_FAIL';
export const OWNER__UPDATE_RESET = 'OWNER__UPDATE_RESET';

export const OWNER__CREATE_REVIEW_REQUEST = 'OWNER__CREATE_REVIEW_REQUEST';
export const OWNER__CREATE_REVIEW_SUCCESS = 'OWNER__CREATE_REVIEW_SUCCESS';
export const OWNER__CREATE_REVIEW_FAIL = 'OWNER__CREATE_REVIEW_FAIL';
export const OWNER__CREATE_REVIEW_RESET = 'OWNER__CREATE_REVIEW_RESET';

export const OWNER__TOP_REQUEST = 'OWNER__TOP_REQUEST';
export const OWNER__TOP_SUCCESS = 'OWNER__TOP_SUCCESS';
export const OWNER__TOP_FAIL = 'OWNER__TOP_FAIL';
