import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Prime Fitness</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="cover">
        <div className="containter text-center py-5">
          <h1 className=" display-3 py-4 mr-3 mt-2">Prime Fitness</h1>
          <p className="display-6 fs-3 text-light fw-semi-bold">
            Find a membership thats right for you.
          </p>
          {/* <Search /> */}
          <Link className="btn btn-md mt-5" href="/sessions/Session/">
            View Memberships
          </Link>
          <div className="container pt-5 mt-5">
            <ul className="nav justify-content-center list-unstyled d-flex pt-5 ">
              <li className="ms-3">
                <Link className="text-muted" href="/">
                  <i className="social-icons fab fa-facebook-f m-1"></i>
                </Link>
              </li>
              <li className="ms-3">
                <Link className="text-muted" href="/">
                  <i className="social-icons fab fa-instagram m-1 "></i>
                </Link>
              </li>
              <li className="ms-3">
                <Link className="text-muted" href="/">
                  <i className=" social-icons fa-brands fa-youtube m-1"></i>
                </Link>
              </li>
              <li className="ms-3">
                <Link className="text-muted" href="/">
                  <i className=" social-icons fa-brands fa-tiktok m-1"></i>
                </Link>
              </li>
            </ul>
            <p className="text-light pt-1">© Copyright 2024 Prime Fitness</p>
          </div>
        </div>
      </div>
    </>
  );
}
