# Generated by Django 4.1.4 on 2023-01-02 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(
                    blank=True, max_length=200, null=True)),
                ('days', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.CharField(blank=True, max_length=200, null=True)),
                ('group', models.CharField(blank=True, max_length=200, null=True)),
                ('memberships', models.CharField(
                    blank=True, max_length=200, null=True)),
                ('virtualSession', models.CharField(
                    blank=True, max_length=200, null=True)),
                ('chat', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=7, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False,
                 primary_key=True, serialize=False)),
                ('user', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(
                    blank=True, max_length=200, null=True)),
                ('days', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.CharField(blank=True, max_length=200, null=True)),
                ('group', models.CharField(blank=True, max_length=200, null=True)),
                ('memberships', models.CharField(
                    blank=True, max_length=200, null=True)),
                ('virtualSession', models.CharField(
                    blank=True, max_length=200, null=True)),
                ('chat', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=7, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False,
                 primary_key=True, serialize=False)),
                ('user', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=7, null=True)),
                ('total', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=7, null=True)),
                ('annualFee', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=7, null=True)),
                ('commitment', models.CharField(
                    blank=True, max_length=200, null=True)),
                ('description', models.CharField(
                    blank=True, max_length=200, null=True)),
                ('accsess', models.CharField(blank=True, max_length=200, null=True)),
                ('discounts', models.CharField(
                    blank=True, max_length=200, null=True)),
                ('security', models.CharField(blank=True, max_length=200, null=True)),
                ('guest', models.CharField(blank=True, max_length=200, null=True)),
                ('wifi', models.CharField(blank=True, max_length=200, null=True)),
                ('session', models.CharField(blank=True, max_length=200, null=True)),
                ('training', models.CharField(blank=True, max_length=200, null=True)),
                ('tan', models.CharField(blank=True, max_length=200, null=True)),
                ('massage', models.CharField(blank=True, max_length=200, null=True)),
                ('spa', models.CharField(blank=True, max_length=200, null=True)),
                ('wellness', models.CharField(blank=True, max_length=200, null=True)),
                ('verified', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=7, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False,
                 primary_key=True, serialize=False)),
                ('user', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('guide', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(
                    blank=True, max_length=200, null=True)),
                ('days', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment', models.CharField(
                    blank=True, max_length=200, null=True)),
                ('slot', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=7, null=True)),
                ('slot2', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=7, null=True)),
                ('slot3', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=7, null=True)),
                ('slot4', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=7, null=True)),
                ('verified', models.CharField(blank=True, max_length=200, null=True)),
                ('wellness', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=7, null=True)),
                ('createdAt', models.DateTimeField(
                    auto_now_add=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(editable=False,
                 primary_key=True, serialize=False)),
                ('user', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
