# Generated by Django 4.1.4 on 2023-01-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='slot',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='slot2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='slot3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='slot4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
