# Generated by Django 4.1.4 on 2023-01-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_guide_slot_alter_guide_slot2_alter_guide_slot3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='guest',
            new_name='guests',
        ),
    ]
