# Generated by Django 4.1.4 on 2023-01-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_guest_member_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='id',
            new_name='_id',
        ),
    ]
