# Generated by Django 4.1.4 on 2023-01-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_id_owner__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='_id',
            new_name='id',
        ),
    ]
