# Generated by Django 4.1.4 on 2023-01-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename__id_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
