# Generated by Django 4.1.4 on 2023-01-06 00:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0015_alter_promo_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guide',
            new_name='Guides',
        ),
    ]
