# Generated by Django 4.1.4 on 2023-01-06 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0016_rename_guide_guides'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='Owners',
        ),
    ]
