# Generated by Django 4.1.4 on 2023-01-07 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_owner_owners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='id',
            new_name='_id',
        ),
    ]
