trainers = [
    {
        'id': '1',
        'title': 'Tai-Chi',
        'instructor': 'Persaonal Trainer',
        'name': 'Kaylee Smith',
        'email': 'smithkaylee@gmail.com',
        'phone': 'xxx-xxxx',
        'bio': 'Kaley is a certified tai-chi-yoga instructor with over 5 years of experience. She has a passion for tai-chi-yoga and loves to share her knowledge with others. She is a certified yoga instructor with over 10 years of experience. She has a passion for yoga and loves to share her knowledge with others.',
        'description':
        'Welcome to the ultimate mind body experiance here at prime fitness, There is a broad variety of yoga practices, and goals in Hinduism, Buddhism, and Jainism, that we help our members achieve.',
        'image': '../images/trainers/trainer1.jpg',
        'photo': '../images/bio/bio10.jpg',
        'cover': '../images/bio/bio11.jpg',
        'profile': '../images/profile/profile11.jpg',
        'experience': 'Experience: 5 years',
        'days': 'Monday, Wednesday, Friday',
        'time': '10am - 11am  6pm - 7pm',
        'level': 'Beginner to yogi',
        'group': 'Personal training',
        'memberships': 'Memberships: included in the All in plan',
        'virtualSession': 'Virtual Classes',
        'nutrition': 'Nutrition Wellness',
        'chat': 'Weekly chats',
        'rating': 'rating: 5',
    },
    {
        'id': '2',
        'title': 'Around the world',
        'instructor': 'Personal Trainer',
        'name': 'Chelsey Kirk',
        'email': 'kirkchelsey@gmail.com',
        'phone': 'xxx-xxxx',
        'bio': 'Chelsey is a certified marathon runner and cardio instructor with over 5 years of experience. She has a passion for cycling and loves to share her knowledge with others. She is a certified cycling instructor with over 10 years of experience. She has a passion for cycling and loves to share her knowledge with others.',
        'description':
        'Cycling is the use of bicycles for transport, recreation, exercise or sport. People engaged in cycling are referred to as "cyclists", "bikers", or less commonly, as "bicyclists".',
        'image': '../images/trainers/trainer2.jpg',
        'photo': '../images/bio/bio13.jpg',
        'cover': '../images/bio/bio12.jpg',
        'profile': '../images/profile/profile10.jpg',
        'experience': 'Experience: 5 years',
        'days': 'Tuesday, Thursday, Saturday',
        'time': '10am - 11am,  6pm - 7pm',
        'level': 'Beginner to pro',
        'group': 'Personal training',
        'memberships': 'Memberships: included in the All in plan',
        'virtualSession': 'Virtual Classes',
        'nutrition': 'Nutrition Wellness',
        'chat': 'Weekly chats',
        'rating': 'rating: 5',
    },

    {
        'id': '3',
        'title': 'Body Break',
        'instructor': 'Personal Trainer',
        'name': 'Travis Owens',
        'email': 'owenstravis@gmail.com',
        'phone': 'xxx-xxxx',
        'bio': 'Travis is a certified body break instructor with over 5 years of experience. He has a passion for body break and loves to share his knowledge with others. He is a certified body break instructor with over 10 years of experience. He has a passion for body break and loves to share his knowledge with others.',
        'description':
        'Body Break is a 30-minute workout that combines cardio, strength, and core training. It’s a great way to get your heart rate up and burn calories. It’s also a great way to get your heart rate up and burn calories.',
        'image': '../images/trainers/trainer3.jpg',
        'photo': '../images/bio/bio14.jpg',
        'cover': '../images/bio/bio15.jpg',
        'profile': '../images/profile/profile12.jpg',
        'experience': 'Experience: 4 years',
        'days': 'Tuesday, Thursday, Friday',
        'time': '6pm - 7pm',
        'level': 'Beginner to pro',
        'group': 'Personal training',
        'memberships': 'Memberships: included in the All in plan',
        'virtualSession': 'Virtual Classes',
        'nutrition': 'Nutrition Wellness',
        'chat': 'Weekly chats',
        'rating': 'rating: 5',
    },
    {
        'id': '4',
        'title': 'Crossfit',
        'instructor': 'Personal Trainer',
        'name': 'Samantha Scott',
        'email': 'scottsamantha@gmail.com',
        'phone': 'xxx-xxxx',
        'bio': 'Sam is a certified crossfit instructor with over 8 years of experience. He has a passion for crossfit and loves to share his knowledge with others. He is a certified crossfit instructor with over 10 years of experience. He has a passion for crossfit and loves to share his knowledge with others.',
        'description':
        'CrossFit is a strength and conditioning program that uses high-intensity, constantly varied functional movements performed at high intensity.',
        'image': '../images/trainers/trainer4.jpg',
        'photo': '../images/bio/bio16.jpg',
        'cover': '../images/bio/bio17.jpg',
        'profile': '../images/profile/profile13.jpg',
        'experience': ' Experience: 8 years',
        'days': 'Monday, Wednesday, Friday',
        'time': '6pm - 7pm',
        'level': 'Beginner to pro',
        'group': 'Personal training',
        'memberships': 'Memberships: included in the All in plan',
        'virtualSession': 'Virtual Classes',
        'nutrition': 'Nutrition Wellness',
        'chat': 'Weekly chats',
        'rating': 'rating: 5',
    },
]
